# Generated by Django 2.0.5 on 2018-05-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(verbose_name='年代'),
        ),
    ]
