# Generated by Django 2.0.5 on 2018-05-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikki', '0002_auto_20180525_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=5, verbose_name='年代'),
        ),
    ]
