# Generated by Django 2.0.5 on 2018-05-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikki', '0003_auto_20180525_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='本文'),
        ),
    ]
