# Generated by Django 2.0.5 on 2018-05-25 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nikki', '0004_auto_20180525_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='名無し', max_length=30, verbose_name='お名前')),
                ('test', models.TextField(verbose_name='本文')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nikki.Article', verbose_name='紐づく記事')),
            ],
        ),
    ]
