# Generated by Django 2.0.5 on 2018-06-07 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nikki', '0008_auto_20180607_0307'),
        ('nikki', '0011_auto_20180605_1857'),
    ]

    operations = [
    ]
