# Generated by Django 2.0.5 on 2018-06-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikki', '0013_article_failure_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='failure_image',
            field=models.IntegerField(null=True, verbose_name='失敗の画像イメージ'),
        ),
    ]
